In [ ]:
!pip install faker

Collecting faker
  Downloading faker-40.28.1-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.28.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 27.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.28.1

In [ ]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

In [ ]:
fake = Faker('en_IN')

random.seed(42)
np.random.seed(42)

NUM_CUSTOMERS = 10000

CURRENT_DATE = datetime.today()

In [ ]:
cities = {
    "Mumbai": "Maharashtra",
    "Pune": "Maharashtra",
    "Delhi": "Delhi",
    "Noida": "Uttar Pradesh",
    "Lucknow": "Uttar Pradesh",
    "Jaipur": "Rajasthan",
    "Ahmedabad": "Gujarat",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Chennai": "Tamil Nadu",
    "Kolkata": "West Bengal",
    "Indore": "Madhya Pradesh",
    "Chandigarh": "Chandigarh",
    "Kochi": "Kerala",
    "Gurugram": "Haryana"
}

segments = ["Consumer","Corporate","Small Business"]
segment_prob = [0.70,0.20,0.10]

channels = ["Website","Mobile App","Physical Store"]
channel_prob = [0.35,0.45,0.20]

occupations = [
    "Software Engineer",
    "Teacher",
    "Doctor",
    "Business Owner",
    "Student",
    "Government Employee",
    "Consultant",
    "Sales Executive",
    "Marketing Manager",
    "Chartered Accountant",
    "Lawyer",
    "Freelancer"
]

In [ ]:
customers = []

for cid in range(1, NUM_CUSTOMERS + 1):

    gender = random.choice(["Male","Female"])

    if gender == "Male":
        first_name = fake.first_name_male()
    else:
        first_name = fake.first_name_female()

    last_name = fake.last_name()

    age = random.randint(18,70)

    dob = CURRENT_DATE - timedelta(days=age*365 + random.randint(0,364))

    city = random.choice(list(cities.keys()))
    state = cities[city]

    annual_income = int(np.random.normal(800000,400000))
    annual_income = max(250000,annual_income)

    registration_date = fake.date_between(
        start_date='-5y',
        end_date='today'
    )

    customer_segment = np.random.choice(
        segments,
        p=segment_prob
    )

    preferred_channel = np.random.choice(
        channels,
        p=channel_prob
    )

    occupation = random.choice(occupations)

    total_orders = random.randint(1,80)

    avg_order_value = int(
        annual_income/180 +
        np.random.normal(1000,500)
    )

    avg_order_value = max(500,avg_order_value)

    lifetime_spend = total_orders * avg_order_value

    if lifetime_spend < 30000:
        loyalty = "Bronze"
    elif lifetime_spend < 80000:
        loyalty = "Silver"
    elif lifetime_spend < 180000:
        loyalty = "Gold"
    else:
        loyalty = "Platinum"

    if loyalty=="Bronze":
        churn = random.randint(60,95)
    elif loyalty=="Silver":
        churn = random.randint(35,65)
    elif loyalty=="Gold":
        churn = random.randint(15,40)
    else:
        churn = random.randint(1,20)

    customers.append([
        cid,
        first_name,
        last_name,
        gender,
        age,
        dob.date(),
        city,
        state,
        fake.postcode(),
        "India",
        registration_date,
        customer_segment,
        loyalty,
        preferred_channel,
        annual_income,
        occupation,
        fake.email(),
        fake.phone_number(),
        total_orders,
        avg_order_value,
        lifetime_spend,
        churn,
        random.choice([True,True,True,False])
    ])

In [ ]:
columns = [
    "customer_id",
    "first_name",
    "last_name",
    "gender",
    "age",
    "date_of_birth",
    "city",
    "state",
    "pincode",
    "country",
    "registration_date",
    "customer_segment",
    "loyalty_tier",
    "preferred_channel",
    "annual_income",
    "occupation",
    "email",
    "phone",
    "total_orders",
    "avg_order_value",
    "lifetime_spend",
    "churn_risk",
    "is_active"
]

dim_customer = pd.DataFrame(customers, columns=columns)

dim_customer.head()

,customer_id,first_name,last_name,gender,age,date_of_birth,city,state,pincode,country,...,preferred_channel,annual_income,occupation,email,phone,total_orders,avg_order_value,lifetime_spend,churn_risk,is_active
0,1,Abdul,Lata,Male,19,2007-02-21,Noida,Uttar Pradesh,630028,India,...,Mobile App,998685,Business Owner,devamakshi@example.net,+915447198330,18,6479,116622,38,True
1,2,Aarnav,Grover,Male,55,1970-12-16,Mumbai,Maharashtra,214463,India,...,Physical Store,706338,Software Engineer,waliachasmum@example.org,+918734075546,12,4807,57684,41,True
2,3,Balveer,Dyal,Male,53,1973-04-09,Indore,Madhya Pradesh,589411,India,...,Physical Store,1431685,Lawyer,dsanghvi@example.net,05595822289,70,9337,653590,14,True
3,4,Vritti,Loyal,Female,55,1971-02-28,Chandigarh,Chandigarh,572873,India,...,Website,612210,Software Engineer,uwadhwa@example.org,1529946925,21,4672,98112,37,False
4,5,Hema,Sengupta,Female,35,1991-04-27,Noida,Uttar Pradesh,171761,India,...,Website,896784,Government Employee,tataleela@example.org,02609885773,14,5025,70350,37,False

In [ ]:
print("Shape :", dim_customer.shape)

print("\nNull Values")
print(dim_customer.isnull().sum())

print("\nDuplicate Customer IDs")
print(dim_customer.customer_id.duplicated().sum())

print("\nLoyalty Distribution")
print(dim_customer.loyalty_tier.value_counts())

print("\nCustomer Segment Distribution")
print(dim_customer.customer_segment.value_counts())

print("\nChannel Distribution")
print(dim_customer.preferred_channel.value_counts())

Shape : (10000, 23)

Null Values
customer_id          0
first_name           0
last_name            0
gender               0
age                  0
date_of_birth        0
city                 0
state                0
pincode              0
country              0
registration_date    0
customer_segment     0
loyalty_tier         0
preferred_channel    0
annual_income        0
occupation           0
email                0
phone                0
total_orders         0
avg_order_value      0
lifetime_spend       0
churn_risk           0
is_active            0
dtype: int64

Duplicate Customer IDs
0

Loyalty Distribution
loyalty_tier
Platinum    5264
Gold        2596
Silver      1378
Bronze       762
Name: count, dtype: int64

Customer Segment Distribution
customer_segment
Consumer          7062
Corporate         1915
Small Business    1023
Name: count, dtype: int64

Channel Distribution
preferred_channel
Mobile App        4474
Website           3524
Physical Store    2002
Name: count, dtype: int64

In [ ]:
categories = {
    "Electronics": [
        "Mobile",
        "Laptop",
        "Headphones",
        "Smart Watch",
        "Camera"
    ],
    "Fashion": [
        "Men Clothing",
        "Women Clothing",
        "Shoes",
        "Accessories"
    ],
    "Home & Kitchen": [
        "Furniture",
        "Cookware",
        "Appliances"
    ],
    "Beauty": [
        "Skin Care",
        "Hair Care",
        "Makeup"
    ],
    "Sports": [
        "Fitness",
        "Outdoor",
        "Cycling"
    ],
    "Groceries": [
        "Beverages",
        "Snacks",
        "Dairy"
    ]
}

dim_customer.csv exported successfully.

In [ ]:
categories = {
    "Electronics": [
        "Mobile",
        "Laptop",
        "Headphones",
        "Smart Watch",
        "Camera"
    ],
    "Fashion": [
        "Men Clothing",
        "Women Clothing",
        "Shoes",
        "Accessories"
    ],
    "Home & Kitchen": [
        "Furniture",
        "Cookware",
        "Appliances"
    ],
    "Beauty": [
        "Skin Care",
        "Hair Care",
        "Makeup"
    ],
    "Sports": [
        "Fitness",
        "Outdoor",
        "Cycling"
    ],
    "Groceries": [
        "Beverages",
        "Snacks",
        "Dairy"
    ]
}

In [ ]:
from google.colab import files

files.download("dim_customer.csv")

In [ ]:
from google.colab import files

files.download("dim_customer.csv")

In [ ]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta
from google.colab import files

In [ ]:
fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)

NUM_PRODUCTS = 2000
TODAY = datetime.today()

In [ ]:
category_dict = {
    "Electronics": {
        "subcategories": ["Mobile","Laptop","Tablet","Headphones","Smartwatch"],
        "brands": ["Apple","Samsung","Sony","Dell","HP","Lenovo","Boat","JBL"],
        "cost": (2000,70000),
        "margin": (0.18,0.35),
        "warranty": (12,24)
    },

    "Fashion": {
        "subcategories": ["Men Clothing","Women Clothing","Shoes","Accessories"],
        "brands": ["Nike","Adidas","Puma","Levis","Allen Solly","Van Heusen"],
        "cost": (300,4000),
        "margin": (0.30,0.60),
        "warranty": (0,0)
    },

    "Home & Kitchen": {
        "subcategories": ["Furniture","Kitchen Appliances","Home Decor"],
        "brands": ["Prestige","Philips","Milton","Borosil"],
        "cost": (500,15000),
        "margin": (0.25,0.45),
        "warranty": (6,24)
    },

    "Beauty": {
        "subcategories": ["Skin Care","Hair Care","Makeup"],
        "brands": ["Lakme","Loreal","Nivea","Maybelline","Dove"],
        "cost": (100,1500),
        "margin": (0.35,0.60),
        "warranty": (0,0)
    },

    "Sports": {
        "subcategories": ["Fitness","Outdoor","Cycling"],
        "brands": ["Nike","Adidas","Decathlon","Puma"],
        "cost": (500,12000),
        "margin": (0.25,0.50),
        "warranty": (6,18)
    },

    "Grocery": {
        "subcategories": ["Snacks","Beverages","Dairy"],
        "brands": ["Amul","Nestle","Britannia","Pepsi","Coca Cola"],
        "cost": (20,600),
        "margin": (0.15,0.30),
        "warranty": (0,0)
    }
}

In [ ]:
product_names = {

"Mobile":["Ultra","Pro","Max","Lite","Prime","Neo"],

"Laptop":["Book","Air","Notebook","Elite","Slim"],

"Tablet":["Pad","Tab","SmartTab"],

"Headphones":["Bass","Studio","Pods","AirSound"],

"Smartwatch":["Fit","Watch","Pulse"],

"Men Clothing":["Shirt","Jeans","Jacket","T-Shirt"],

"Women Clothing":["Top","Dress","Kurti","Jeans"],

"Shoes":["Running Shoes","Sneakers","Sports Shoes"],

"Accessories":["Wallet","Belt","Cap","Bag"],

"Furniture":["Chair","Table","Sofa","Desk"],

"Kitchen Appliances":["Mixer","Cooker","Toaster"],

"Home Decor":["Lamp","Mirror","Painting"],

"Skin Care":["Face Wash","Moisturizer","Serum"],

"Hair Care":["Shampoo","Conditioner","Hair Oil"],

"Makeup":["Lipstick","Foundation","Mascara"],

"Fitness":["Dumbbell","Yoga Mat","Resistance Band"],

"Outdoor":["Tent","Backpack","Sleeping Bag"],

"Cycling":["Cycle Helmet","Mountain Bike"],

"Snacks":["Chips","Cookies","Namkeen"],

"Beverages":["Juice","Soft Drink","Energy Drink"],

"Dairy":["Milk","Butter","Cheese"]
}

In [ ]:
products = []

for pid in range(1, NUM_PRODUCTS+1):

    category = random.choice(list(category_dict.keys()))

    info = category_dict[category]

    subcategory = random.choice(info["subcategories"])

    brand = random.choice(info["brands"])

    product_suffix = random.choice(product_names[subcategory])

    product_name = f"{brand} {product_suffix}"

    supplier_id = random.randint(1,300)

    cost_price = random.randint(info["cost"][0],info["cost"][1])

    margin = round(random.uniform(info["margin"][0],info["margin"][1]),2)

    selling_price = round(cost_price*(1+margin),2)

    discount = random.choice([0,5,10,15,20,25])

    launch_date = fake.date_between(start_date="-4y",end_date="today")

    rating = round(random.uniform(3.5,5.0),1)

    review_count = int(abs(np.random.normal(500,250)))

    warranty = random.randint(info["warranty"][0],info["warranty"][1])

    weight = round(random.uniform(0.1,20),2)

    stock_status = np.random.choice(

        ["In Stock","Low Stock","Out of Stock"],

        p=[0.75,0.18,0.07]

    )

    is_active = random.choice([True,True,True,False])

    products.append([

        pid,

        product_name,

        category,

        subcategory,

        brand,

        supplier_id,

        cost_price,

        selling_price,

        discount,

        round(margin*100,2),

        launch_date,

        rating,

        review_count,

        warranty,

        weight,

        stock_status,

        is_active

    ])

In [ ]:
columns=[

"product_id",

"product_name",

"category",

"sub_category",

"brand",

"supplier_id",

"cost_price",

"selling_price",

"discount_percent",

"profit_margin",

"launch_date",

"product_rating",

"review_count",

"warranty_months",

"weight_kg",

"stock_status",

"is_active"

]

dim_product=pd.DataFrame(products,columns=columns)

dim_product.head()

,product_id,product_name,category,sub_category,brand,supplier_id,cost_price,selling_price,discount_percent,profit_margin,launch_date,product_rating,review_count,warranty_months,weight_kg,stock_status,is_active
0,1,Amul Namkeen,Grocery,Snacks,Amul,141,270,318.60,25,18.0,2025-12-18,3.7,624,0,11.85,In Stock,True
1,2,Dell Pro,Electronics,Mobile,Dell,259,5478,7011.84,25,28.0,2023-03-25,4.5,465,20,8.45,In Stock,False
2,3,Nike Tent,Sports,Outdoor,Nike,217,6074,8017.68,5,32.0,2025-06-08,4.9,441,11,2.13,In Stock,False
3,4,Lenovo SmartTab,Electronics,Tablet,Lenovo,136,7695,10003.50,20,30.0,2024-05-18,3.7,441,18,1.67,Low Stock,True
4,5,Britannia Cheese,Grocery,Dairy,Britannia,99,91,105.56,5,16.0,2022-10-11,4.7,894,0,17.12,In Stock,True

In [ ]:
dim_product["discounted_price"] = (
    dim_product["selling_price"] *
    (1-dim_product["discount_percent"]/100)
).round(2)

dim_product["expected_profit"] = (
    dim_product["selling_price"] -
    dim_product["cost_price"]
).round(2)

In [ ]:
print("="*50)

print("Shape")

print(dim_product.shape)

print("="*50)

print("Null Values")

print(dim_product.isnull().sum())

print("="*50)

print("Duplicate Product IDs")

print(dim_product.product_id.duplicated().sum())

print("="*50)

print("Category Distribution")

print(dim_product.category.value_counts())

print("="*50)

print("Average Selling Price")

print(dim_product.groupby("category")["selling_price"].mean().round(2))

print("="*50)

print("Stock Status")

print(dim_product.stock_status.value_counts())

==================================================
Shape
(2000, 19)
==================================================
Null Values
product_id          0
product_name        0
category            0
sub_category        0
brand               0
supplier_id         0
cost_price          0
selling_price       0
discount_percent    0
profit_margin       0
launch_date         0
product_rating      0
review_count        0
warranty_months     0
weight_kg           0
stock_status        0
is_active           0
discounted_price    0
expected_profit     0
dtype: int64
==================================================
Duplicate Product IDs
0
==================================================
Category Distribution
category
Sports            352
Beauty            349
Fashion           337
Home & Kitchen    329
Electronics       326
Grocery           307
Name: count, dtype: int64
==================================================
Average Selling Price
category
Beauty             1155.05
Electronics       43849.00
Fashion            3038.38
Grocery             369.63
Home & Kitchen    10220.50
Sports             8888.13
Name: selling_price, dtype: float64
==================================================
Stock Status
stock_status
In Stock        1504
Low Stock        364
Out of Stock     132
Name: count, dtype: int64

In [ ]:
dim_product.describe(include="all")

,product_id,product_name,category,sub_category,brand,supplier_id,cost_price,selling_price,discount_percent,profit_margin,launch_date,product_rating,review_count,warranty_months,weight_kg,stock_status,is_active,discounted_price,expected_profit
count,2000.000000,2000,2000,2000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000,2000.000000,2000.000000
unique,NaN,379,6,21,29,NaN,NaN,NaN,NaN,NaN,1089,NaN,NaN,NaN,NaN,3,2,NaN,NaN
top,NaN,Adidas Mountain Bike,Sports,Cycling,Nike,NaN,NaN,NaN,NaN,NaN,2023-03-04,NaN,NaN,NaN,NaN,In Stock,True,NaN,NaN
freq,NaN,22,352,134,149,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1504,1486,NaN,NaN
mean,1000.500000,NaN,NaN,NaN,NaN,150.756000,8573.245000,11163.231145,12.685000,35.979000,NaN,4.263750,511.383000,7.490000,10.244245,NaN,NaN,9691.075670,2589.986145
std,577.494589,NaN,NaN,NaN,NaN,87.337909,14297.491562,18066.707763,8.583566,11.055572,NaN,0.438528,239.672772,8.259722,5.731001,NaN,NaN,15666.447078,3856.956306
min,1.000000,NaN,NaN,NaN,NaN,1.000000,22.000000,26.400000,0.000000,15.000000,NaN,3.500000,1.000000,0.000000,0.120000,NaN,NaN,19.800000,4.400000
25%,500.750000,NaN,NaN,NaN,NaN,75.000000,694.250000,1030.200000,5.000000,27.000000,NaN,3.900000,340.000000,0.000000,5.347500,NaN,NaN,853.560000,308.805000
50%,1000.500000,NaN,NaN,NaN,NaN,151.000000,2773.000000,3861.700000,15.000000,35.000000,NaN,4.300000,508.500000,6.000000,10.325000,NaN,NaN,3366.070000,1081.600000
75%,1500.250000,NaN,NaN,NaN,NaN,224.000000,9303.250000,12462.067500,20.000000,44.000000,NaN,4.600000,667.000000,15.000000,15.262500,NaN,NaN,10800.412500,3162.480000
max,2000.000000,NaN,NaN,NaN,NaN,300.000000,69135.000000,90304.850000,25.000000,60.000000,NaN,5.000000,1481.000000,24.000000,20.000000,NaN,NaN,87909.360000,22132.250000

In [ ]:
dim_product.to_csv("dim_product.csv",index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

In [ ]:
files.download("dim_product.csv")

In [ ]:
!pip install faker -q

In [ ]:
import pandas as pd
import numpy as np
import random

from faker import Faker
from datetime import datetime
from google.colab import files

In [ ]:
fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)

NUM_STORES = 100

In [ ]:
city_data = {
    "Mumbai": ("Maharashtra","West",19.0760,72.8777),
    "Pune": ("Maharashtra","West",18.5204,73.8567),
    "Ahmedabad": ("Gujarat","West",23.0225,72.5714),
    "Surat": ("Gujarat","West",21.1702,72.8311),

    "Delhi": ("Delhi","North",28.7041,77.1025),
    "Noida": ("Uttar Pradesh","North",28.5355,77.3910),
    "Lucknow": ("Uttar Pradesh","North",26.8467,80.9462),
    "Chandigarh": ("Chandigarh","North",30.7333,76.7794),
    "Jaipur": ("Rajasthan","North",26.9124,75.7873),

    "Bengaluru": ("Karnataka","South",12.9716,77.5946),
    "Hyderabad": ("Telangana","South",17.3850,78.4867),
    "Chennai": ("Tamil Nadu","South",13.0827,80.2707),
    "Kochi": ("Kerala","South",9.9312,76.2673),
    "Coimbatore": ("Tamil Nadu","South",11.0168,76.9558),

    "Kolkata": ("West Bengal","East",22.5726,88.3639),
    "Bhubaneswar": ("Odisha","East",20.2961,85.8245),
    "Patna": ("Bihar","East",25.5941,85.1376),
    "Guwahati": ("Assam","East",26.1445,91.7362),
    "Ranchi": ("Jharkhand","East",23.3441,85.3096)
}

In [ ]:
store_types = [
    "Mall",
    "High Street",
    "Express",
    "Warehouse"
]

store_prob = [
    0.30,
    0.30,
    0.25,
    0.15
]

In [ ]:
stores = []

for sid in range(1, NUM_STORES + 1):

    city = random.choice(list(city_data.keys()))

    state, region, lat, lon = city_data[city]

    store_type = np.random.choice(store_types, p=store_prob)

    if store_type == "Mall":
        size = random.randint(12000,22000)
        employees = random.randint(45,80)
        rent = random.randint(25000000,45000000)

    elif store_type == "High Street":
        size = random.randint(7000,12000)
        employees = random.randint(25,45)
        rent = random.randint(12000000,25000000)

    elif store_type == "Express":
        size = random.randint(2500,6000)
        employees = random.randint(10,25)
        rent = random.randint(4000000,12000000)

    else:
        size = random.randint(15000,30000)
        employees = random.randint(20,45)
        rent = random.randint(15000000,35000000)

    manager = fake.name()

    opening_date = fake.date_between(
        start_date="-15y",
        end_date="today"
    )

    stores.append([
        f"S{sid:03}",
        f"RetailX {city} Store",
        city,
        state,
        region,
        store_type,
        opening_date,
        size,
        employees,
        rent,
        round(lat + random.uniform(-0.03,0.03),6),
        round(lon + random.uniform(-0.03,0.03),6),
        manager,
        random.choice([True,True,True,False])
    ])

In [ ]:
columns = [

    "store_id",

    "store_name",

    "city",

    "state",

    "region",

    "store_type",

    "opening_date",

    "store_size_sqft",

    "employees",

    "annual_rent",

    "latitude",

    "longitude",

    "manager_name",

    "is_active"

]

dim_store = pd.DataFrame(stores, columns=columns)

dim_store.head()

,store_id,store_name,city,state,region,store_type,opening_date,store_size_sqft,employees,annual_rent,latitude,longitude,manager_name,is_active
0,S001,RetailX Surat Store,Surat,Gujarat,West,High Street,2017-01-21,7204,33,16108603,21.153593,72.845288,Falak Dhar,True
1,S002,RetailX Ranchi Store,Ranchi,Jharkhand,East,Warehouse,2014-10-18,21912,21,15999828,23.319722,85.293560,Bishakha Rau,True
2,S003,RetailX Guwahati Store,Guwahati,Assam,East,Express,2024-02-19,3314,23,5849189,26.141453,91.722891,Xalak Dhar,True
3,S004,RetailX Noida Store,Noida,Uttar Pradesh,North,High Street,2024-07-13,10462,35,16661907,28.514829,77.418433,Henry Bains,True
4,S005,RetailX Surat Store,Surat,Gujarat,West,Mall,2015-10-18,13519,69,28245263,21.161739,72.821737,Anjali Bhatia,True

In [ ]:
dim_store["rent_per_sqft"] = (
    dim_store["annual_rent"] /
    dim_store["store_size_sqft"]
).round(2)

dim_store["employee_density"] = (
    dim_store["employees"] /
    dim_store["store_size_sqft"] * 1000
).round(2)

In [ ]:
print("="*50)

print("Shape")

print(dim_store.shape)

print("="*50)

print("Null Values")

print(dim_store.isnull().sum())

print("="*50)

print("Duplicate Store IDs")

print(dim_store.store_id.duplicated().sum())

print("="*50)

print("Region Distribution")

print(dim_store.region.value_counts())

print("="*50)

print("Store Types")

print(dim_store.store_type.value_counts())

print("="*50)

print("Average Employees")

print(
    dim_store.groupby("store_type")["employees"].mean()
)

==================================================
Shape
(100, 16)
==================================================
Null Values
store_id            0
store_name          0
city                0
state               0
region              0
store_type          0
opening_date        0
store_size_sqft     0
employees           0
annual_rent         0
latitude            0
longitude           0
manager_name        0
is_active           0
rent_per_sqft       0
employee_density    0
dtype: int64
==================================================
Duplicate Store IDs
0
==================================================
Region Distribution
region
West     30
North    26
South    24
East     20
Name: count, dtype: int64
==================================================
Store Types
store_type
Mall           34
High Street    29
Express        24
Warehouse      13
Name: count, dtype: int64
==================================================
Average Employees
store_type
Express        17.750000
High Street    36.206897
Mall           62.588235
Warehouse      32.230769
Name: employees, dtype: float64

In [ ]:
dim_store.describe(include="all")

,store_id,store_name,city,state,region,store_type,opening_date,store_size_sqft,employees,annual_rent,latitude,longitude,manager_name,is_active,rent_per_sqft,employee_density
count,100,100,100,100,100,100,100,100.00000,100.000000,1.000000e+02,100.000000,100.000000,100,100,100.000000,100.000000
unique,100,19,19,15,4,4,99,NaN,NaN,NaN,NaN,NaN,100,2,NaN,NaN
top,S001,RetailX Ahmedabad Store,Ahmedabad,Gujarat,West,Mall,2022-12-24,NaN,NaN,NaN,NaN,NaN,Falak Dhar,True,NaN,NaN
freq,1,15,15,23,30,34,2,NaN,NaN,NaN,NaN,NaN,1,75,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12913.53000,40.230000,2.210080e+07,21.822075,78.122988,NaN,NaN,1872.811400,3.622500
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7221.84152,19.185882,1.155353e+07,5.753056,5.368091,NaN,NaN,660.729317,1.462437
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2748.00000,10.000000,4.421818e+06,9.903863,72.542623,NaN,NaN,633.820000,0.930000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7227.25000,25.000000,1.259381e+07,18.547674,72.903212,NaN,NaN,1428.725000,2.620000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11604.00000,40.000000,2.043679e+07,23.006437,77.086763,NaN,NaN,1902.370000,3.595000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18556.50000,55.500000,3.128646e+07,26.826198,80.260303,NaN,NaN,2252.172500,4.442500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29960.00000,80.000000,4.499470e+07,30.760117,91.747837,NaN,NaN,3678.570000,8.010000

In [ ]:
dim_store.to_csv("dim_store.csv", index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

In [ ]:
files.download("dim_store.csv")