In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("EnterpriseDW.db")

print("Database Created Successfully")

Database Created Successfully

In [3]:
date = pd.read_csv("Dim_Date.csv")

customers = pd.read_csv("Dim_Customers.csv")

products = pd.read_csv("Dim_Products.csv")

stores = pd.read_csv("Dim_Stores.csv")

suppliers = pd.read_csv("Dim_Suppliers.csv")

sales = pd.read_csv("Fact_Sales.csv")

inventory = pd.read_csv("Fact_Inventory.csv")

marketing = pd.read_csv("Fact_Marketing.csv")

support = pd.read_csv("Fact_Support.csv")

In [4]:
date.to_sql(
    "Dim_Date",
    conn,
    if_exists="replace",
    index=False
)

customers.to_sql(
    "Dim_Customers",
    conn,
    if_exists="replace",
    index=False
)

products.to_sql(
    "Dim_Products",
    conn,
    if_exists="replace",
    index=False
)

stores.to_sql(
    "Dim_Stores",
    conn,
    if_exists="replace",
    index=False
)

suppliers.to_sql(
    "Dim_Suppliers",
    conn,
    if_exists="replace",
    index=False
)

sales.to_sql(
    "Fact_Sales",
    conn,
    if_exists="replace",
    index=False
)

inventory.to_sql(
    "Fact_Inventory",
    conn,
    if_exists="replace",
    index=False
)

marketing.to_sql(
    "Fact_Marketing",
    conn,
    if_exists="replace",
    index=False
)

support.to_sql(
    "Fact_Support",
    conn,
    if_exists="replace",
    index=False
)

print("All Tables Imported Successfully")

All Tables Imported Successfully

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

pd.read_sql(query, conn)

             name
0   Dim_Customers
1        Dim_Date
2    Dim_Products
3      Dim_Stores
4   Dim_Suppliers
5  Fact_Inventory
6  Fact_Marketing
7      Fact_Sales
8    Fact_Support

In [7]:
tables = [
    "Dim_Date",
    "Dim_Customers",
    "Dim_Products",
    "Dim_Stores",
    "Dim_Suppliers",
    "Fact_Sales",
    "Fact_Inventory",
    "Fact_Marketing",
    "Fact_Support"
]

for table in tables:

    query = f"SELECT COUNT(*) AS Rows FROM {table}"

    print(table)

    print(pd.read_sql(query, conn))

    print("-"*40)

Dim_Date
   Rows
0  2192
----------------------------------------
Dim_Customers
     Rows
0  100000
----------------------------------------
Dim_Products
   Rows
0  5000
----------------------------------------
Dim_Stores
   Rows
0   250
----------------------------------------
Dim_Suppliers
   Rows
0   500
----------------------------------------
Fact_Sales
    Rows
0  27930
----------------------------------------
Fact_Inventory
     Rows
0  200000
----------------------------------------
Fact_Marketing
     Rows
0  100000
----------------------------------------
Fact_Support
     Rows
0  150000
----------------------------------------

In [8]:
query = """
SELECT *
FROM Fact_Sales
LIMIT 5;
"""

pd.read_sql(query, conn)

,Sales_ID,Order_ID,Line_No,Invoice_ID,Date_ID,Customer_ID,Store_ID,Product_ID,Category,Brand,...,Order_Priority,Delivery_Partner,Payment_Status,Invoice_Status,Fulfillment_Status,SLA_Breached,Fraud_Flag,Sales_Source,Currency,Fiscal_Year
0,SAL000000001,ORD0000001,1,INV0000001,20240314,CUST035327,STR0173,PRD02419,Furniture,Nilkamal,...,Low,XpressBees,Paid,Generated,Completed,No,No,Store,INR,2024.0
1,SAL000000002,ORD0000002,1,INV0000002,20240823,CUST045784,STR0034,PRD02295,Electronics,LG,...,Low,Delhivery,Paid,Generated,Completed,No,No,Website,INR,2024.0
2,SAL000000003,ORD0000002,2,INV0000002,20240823,CUST045784,STR0034,PRD03133,Fashion,Allen Solly,...,Low,Ekart,Paid,Generated,Completed,No,No,Mobile App,INR,2024.0
3,SAL000000004,ORD0000002,3,INV0000002,20240823,CUST045784,STR0034,PRD02080,Books,Bloomsbury,...,Low,XpressBees,Paid,Generated,Completed,No,No,Website,INR,2024.0
4,SAL000000005,ORD0000002,4,INV0000002,20240823,CUST045784,STR0034,PRD01125,Fashion,Allen Solly,...,Medium,Ekart,Paid,Generated,Completed,No,No,Website,INR,2024.0

In [9]:
query = """
SELECT
ROUND(SUM(Total_Amount),2) AS Total_Revenue
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Revenue
0   1.109570e+09

In [10]:
query = """
SELECT
COUNT(DISTINCT Order_ID) AS Total_Orders
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Orders
0         16036

In [11]:
query = """
SELECT
COUNT(DISTINCT Order_ID) AS Total_Orders
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Orders
0         16036

In [12]:
query = """
SELECT
COUNT(DISTINCT Customer_ID) AS Total_Customers
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Customers
0            14737

In [13]:
query = """
SELECT

ROUND(
SUM(Total_Amount) /
COUNT(DISTINCT Order_ID),
2
) AS Average_Order_Value

FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Average_Order_Value
0             69192.47

In [14]:
query = """
SELECT *
FROM Dim_Date
LIMIT 5;
"""

pd.read_sql(query, conn)

,Date_ID,Date,Day,Month,Month_Number,Quarter,Year,Week,Day_Name,Is_Weekend,Is_Holiday,Holiday_Name,Financial_Year,Financial_Quarter,Month_End_Flag,Quarter_End_Flag,Festival_Season
0,20200101,2020-01-01,1,January,1,Q1,2020,1,Wednesday,No,Yes,New Year's Day,FY2019-20,FQ4,No,No,No
1,20200102,2020-01-02,2,January,1,Q1,2020,1,Thursday,No,No,None,FY2019-20,FQ4,No,No,No
2,20200103,2020-01-03,3,January,1,Q1,2020,1,Friday,No,No,None,FY2019-20,FQ4,No,No,No
3,20200104,2020-01-04,4,January,1,Q1,2020,1,Saturday,Yes,No,None,FY2019-20,FQ4,No,No,No
4,20200105,2020-01-05,5,January,1,Q1,2020,1,Sunday,Yes,No,None,FY2019-20,FQ4,No,No,No

In [15]:
query = """
SELECT *
FROM Dim_Products
LIMIT 5;
"""

pd.read_sql(query, conn)

,Product_ID,Product_Name,Category,Subcategory,Brand,Supplier_ID,Unit_Cost_INR,Selling_Price_INR,Profit_Margin_Percent,Weight_Kg,Warranty_Months,GST_Rate,Launch_Date,Reorder_Level,Product_Status
0,PRD00001,Cosco Cycling 1,Sports,Cycling,Cosco,SUP0060,11695,16606.90,42,7.15,6,18,2019-04-30,135,Active
1,PRD00002,Samsung Laptop 2,Electronics,Laptop,Samsung,SUP0353,102508,134285.48,31,39.58,24,28,2022-08-28,203,Active
2,PRD00003,Nestle Oil 3,Grocery,Oil,Nestle,SUP0036,508,665.48,31,23.59,12,18,2020-03-17,168,Active
3,PRD00004,Nike Gym 4,Sports,Gym,Nike,SUP0098,8000,11520.00,44,7.62,12,12,2019-07-21,42,Active
4,PRD00005,Nike Badminton 5,Sports,Badminton,Nike,SUP0242,6254,8818.14,41,25.26,36,12,2021-08-13,267,Active

In [16]:
query = """
SELECT *
FROM Dim_Stores
LIMIT 5;
"""

pd.read_sql(query, conn)

,Store_ID,Store_Name,Store_Type,City,State,Region,Warehouse_ID,Manager_ID,Opening_Date,Store_Size_SqFt,Employee_Count,Latitude,Longitude,Annual_Target_INR,Performance_Tier,Status
0,STR0001,Meridian Chennai Store 1,Express,Chennai,Tamil Nadu,South,WH016,EMP1001,2017-07-03,7072,36,13.0827,80.2707,48000000,Silver,Active
1,STR0002,Meridian Visakhapatnam Store 2,Flagship,Visakhapatnam,Andhra Pradesh,South,WH006,EMP1002,2017-06-14,10123,139,17.6868,83.2185,43000000,Platinum,Active
2,STR0003,Meridian Raipur Store 3,Mall,Raipur,Chhattisgarh,Central,WH038,EMP1003,2018-02-13,29023,11,21.2514,81.6296,15000000,Silver,Active
3,STR0004,Meridian Hyderabad Store 4,Express,Hyderabad,Telangana,South,WH022,EMP1004,2016-02-23,5539,107,17.3850,78.4867,11000000,Gold,Active
4,STR0005,Meridian Jaipur Store 5,Express,Jaipur,Rajasthan,North,WH035,EMP1005,2016-05-26,14903,30,26.9124,75.7873,40000000,Gold,Active

In [18]:
query = """
SELECT

p.Category,

ROUND(SUM(f.Total_Amount),2) AS Revenue

FROM Fact_Sales f

JOIN Dim_Products p

ON f.Product_ID = p.Product_ID

GROUP BY p.Category

ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

          Category       Revenue
0      Electronics  3.774956e+08
1        Furniture  2.834564e+08
2  Home Appliances  2.712217e+08
3       Healthcare  4.964681e+07
4           Sports  4.576360e+07
5             Toys  3.408254e+07
6          Fashion  2.104421e+07
7           Beauty  9.703854e+06
8            Books  8.852165e+06
9          Grocery  8.303468e+06

In [20]:
query = """
SELECT

d.Year,

d.Month,

ROUND(SUM(f.Total_Amount),2) AS Revenue

FROM Fact_Sales f

JOIN Dim_Date d

ON f.Date_ID = d.Date_ID

GROUP BY

d.Year,
d.Month_Number,
d.Month

ORDER BY

d.Year,
d.Month_Number;
"""

pd.read_sql(query, conn)

    Year      Month      Revenue
0   2020    January  12234308.63
1   2020   February  15587622.47
2   2020      March  15176945.42
3   2020      April  13356612.23
4   2020        May  12640446.83
..   ...        ...          ...
67  2025     August  18283777.22
68  2025  September  16570659.69
69  2025    October  17840054.11
70  2025   November  17127728.36
71  2025   December  13829451.61

[72 rows x 3 columns]

In [21]:
query = """
SELECT

p.Product_Name,

ROUND(SUM(f.Total_Amount),2) AS Revenue

FROM Fact_Sales f

JOIN Dim_Products p

ON f.Product_ID = p.Product_ID

GROUP BY p.Product_Name

ORDER BY Revenue DESC

LIMIT 10;
"""

pd.read_sql(query, conn)

                     Product_Name     Revenue
0         Samsung Smartwatch 4473  3464259.11
1              Samsung Mobile 397  3156708.72
2                 Samsung TV 3887  3079187.56
3              LG Smartwatch 2139  3057990.36
4         Samsung Smartwatch 1701  2987518.36
5  Whirlpool Washing Machine 2849  2796966.87
6                Sony Laptop 4659  2548221.71
7            Sony Headphones 5000  2515337.42
8                  LG Mobile 3422  2455267.71
9         Samsung Headphones 1273  2435321.20

In [22]:
query = """
SELECT

s.Store_Name,

ROUND(SUM(f.Total_Amount),2) AS Revenue

FROM Fact_Sales f

JOIN Dim_Stores s
ON f.Store_ID = s.Store_ID

GROUP BY
s.Store_Name

ORDER BY Revenue DESC

LIMIT 10;
"""

pd.read_sql(query, conn)

                        Store_Name     Revenue
0         Meridian Bhopal Store 20  7089965.46
1      Meridian Faridabad Store 59  7071167.98
2  Meridian Visakhapatnam Store 50  6610511.33
3     Meridian Hyderabad Store 115  6592647.31
4        Meridian Udaipur Store 90  6573534.72
5         Meridian Ranchi Store 70  6560836.55
6        Meridian Ranchi Store 183  6503099.81
7        Meridian Ranchi Store 169  6486223.43
8        Meridian Indore Store 176  6313813.71
9  Meridian Visakhapatnam Store 12  6222970.01

In [23]:
query = """
SELECT

s.Region,

ROUND(SUM(f.Total_Amount),2) AS Revenue

FROM Fact_Sales f

JOIN Dim_Stores s
ON f.Store_ID = s.Store_ID

GROUP BY
s.Region

ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

    Region       Revenue
0    South  3.125292e+08
1     East  2.772928e+08
2    North  2.599773e+08
3     West  1.594406e+08
4  Central  1.003305e+08

In [24]:
query = """
SELECT

s.Region,

ROUND(SUM(f.Profit),2) AS Profit

FROM Fact_Sales f

JOIN Dim_Stores s
ON f.Store_ID = s.Store_ID

GROUP BY
s.Region

ORDER BY Profit DESC;
"""

pd.read_sql(query, conn)

    Region       Profit
0    South  41495178.44
1     East  36030922.18
2    North  33553312.67
3     West  21584820.23
4  Central  12689694.94

In [25]:
query = """
SELECT
ROUND(SUM(Gross_Sales),2) AS Gross_Sales
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

    Gross_Sales
0  1.054678e+09

In [26]:
query = """
SELECT
ROUND(SUM(Gross_Sales),2) AS Gross_Sales
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

    Gross_Sales
0  1.054678e+09

In [27]:
query = """
SELECT
ROUND(SUM(Discount_Amount),2) AS Total_Discount
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Discount
0     98359128.76

In [28]:
query = """
SELECT
ROUND(SUM(Profit),2) AS Total_Profit
FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Total_Profit
0  1.453539e+08

In [29]:
query = """
SELECT

ROUND(

(SUM(Profit)/SUM(Net_Sales))*100,

2

) AS Gross_Margin_Percentage

FROM Fact_Sales;
"""

pd.read_sql(query, conn)

   Gross_Margin_Percentage
0                     15.2

In [31]:
query = """
SELECT

Payment_Method,

ROUND(SUM(Total_Amount),2) AS Revenue

FROM Fact_Sales

GROUP BY Payment_Method

ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  Payment_Method       Revenue
0            UPI  4.261557e+08
1    Credit Card  2.966127e+08
2     Debit Card  1.942095e+08
3           Cash  1.122639e+08
4    Net Banking  8.032864e+07
5           None           NaN

In [32]:
query = """
SELECT

Payment_Method,

ROUND(SUM(Total_Amount),2) AS Revenue

FROM Fact_Sales

GROUP BY Payment_Method

ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  Payment_Method       Revenue
0            UPI  4.261557e+08
1    Credit Card  2.966127e+08
2     Debit Card  1.942095e+08
3           Cash  1.122639e+08
4    Net Banking  8.032864e+07
5           None           NaN

In [33]:
query = """
SELECT

Sales_Channel,

ROUND(SUM(Total_Amount),2) AS Revenue

FROM Fact_Sales

GROUP BY Sales_Channel

ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  Sales_Channel       Revenue
0        Online  7.251261e+08
1         Store  3.844444e+08
2          None           NaN

In [34]:
query = """
SELECT

d.Year,

d.Month,

ROUND(SUM(f.Profit),2) AS Profit

FROM Fact_Sales f

JOIN Dim_Date d

ON f.Date_ID=d.Date_ID

GROUP BY

d.Year,
d.Month_Number,
d.Month

ORDER BY

d.Year,
d.Month_Number;
"""

pd.read_sql(query, conn)

    Year      Month      Profit
0   2020    January  1584653.46
1   2020   February  2015646.72
2   2020      March  2257228.65
3   2020      April  1922592.06
4   2020        May  1721933.03
..   ...        ...         ...
67  2025     August  2674245.88
68  2025  September  2161385.38
69  2025    October  2363488.54
70  2025   November  2091408.71
71  2025   December  1843652.77

[72 rows x 3 columns]

In [35]:
query = """
SELECT

ROUND(SUM(Inventory_Value),2) AS Total_Inventory_Value

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Total_Inventory_Value
0           2.041240e+12

In [36]:
query = """
SELECT

ROUND(SUM(Inventory_Value),2) AS Total_Inventory_Value

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Total_Inventory_Value
0           2.041240e+12

In [37]:
  query = """
SELECT

ROUND(SUM(Ad_Spend),2) AS Marketing_Spend,

ROUND(SUM(Revenue_Generated),2) AS Revenue_Generated,

ROUND(AVG(ROAS),2) AS Average_ROAS

FROM Fact_Marketing;
"""

pd.read_sql(query, conn)

   Marketing_Spend  Revenue_Generated  Average_ROAS
0     1.385744e+10       2.413681e+11          27.0

In [38]:
query = """
SELECT

s.Store_Name,

ROUND(SUM(i.Inventory_Value),2) AS Inventory_Value

FROM Fact_Inventory i

JOIN Dim_Stores s
ON i.Store_ID = s.Store_ID

GROUP BY s.Store_Name

ORDER BY Inventory_Value DESC;
"""

pd.read_sql(query, conn)

                        Store_Name  Inventory_Value
0     Meridian Faridabad Store 205     1.013769e+10
1    Meridian Coimbatore Store 233     9.801863e+09
2      Meridian Vadodara Store 222     9.758685e+09
3      Meridian New Delhi Store 95     9.442944e+09
4      Meridian Faridabad Store 44     9.331059e+09
..                             ...              ...
245    Meridian Hyderabad Store 66     7.021383e+09
246      Meridian Nagpur Store 143     6.850746e+09
247       Meridian Patna Store 166     6.784088e+09
248    Meridian Ludhiana Store 107     6.754675e+09
249       Meridian Ranchi Store 56     6.523225e+09

[250 rows x 2 columns]

In [39]:
query = """
SELECT

Product_ID,

Closing_Stock,

Reorder_Level

FROM Fact_Inventory

WHERE Closing_Stock < Reorder_Level

ORDER BY Closing_Stock;
"""

pd.read_sql(query, conn)

      Product_ID  Closing_Stock  Reorder_Level
0       PRD01386              0            300
1       PRD02799              0             28
2       PRD01602              0             83
3       PRD00527              0            256
4       PRD01495              0            110
...          ...            ...            ...
18581   PRD00263            295            297
18582   PRD00507            296            299
18583   PRD03178            297            299
18584   PRD02908            297            300
18585   PRD04476            299            300

[18586 rows x 3 columns]

In [40]:
query = """
SELECT

Product_ID,

Closing_Stock,

Reorder_Level

FROM Fact_Inventory

WHERE Closing_Stock < Reorder_Level

ORDER BY Closing_Stock;
"""

pd.read_sql(query, conn)

      Product_ID  Closing_Stock  Reorder_Level
0       PRD01386              0            300
1       PRD02799              0             28
2       PRD01602              0             83
3       PRD00527              0            256
4       PRD01495              0            110
...          ...            ...            ...
18581   PRD00263            295            297
18582   PRD00507            296            299
18583   PRD03178            297            299
18584   PRD02908            297            300
18585   PRD04476            299            300

[18586 rows x 3 columns]

In [41]:
query = """
SELECT

Inventory_Status,

COUNT(*) AS Total_Items

FROM Fact_Inventory

GROUP BY Inventory_Status;
"""

pd.read_sql(query, conn)

  Inventory_Status  Total_Items
0        Low Stock        16494
1           Normal       149222
2     Out of Stock         2092
3        Overstock        32192

In [42]:
query = """
SELECT

Warehouse_ID,

ROUND(SUM(Inventory_Value),2) AS Inventory_Value

FROM Fact_Inventory

GROUP BY Warehouse_ID

ORDER BY Inventory_Value DESC;
"""

pd.read_sql(query, conn)

   Warehouse_ID  Inventory_Value
0         WH037     8.863750e+10
1         WH047     8.857271e+10
2         WH020     8.132627e+10
3         WH050     8.008155e+10
4         WH016     6.661525e+10
5         WH024     6.651105e+10
6         WH049     6.575782e+10
7         WH029     6.526571e+10
8         WH035     5.961324e+10
9         WH027     5.944196e+10
10        WH046     5.850613e+10
11        WH015     5.835653e+10
12        WH031     5.827298e+10
13        WH048     5.730319e+10
14        WH009     4.928440e+10
15        WH036     4.837776e+10
16        WH017     4.702950e+10
17        WH043     4.652742e+10
18        WH040     4.245377e+10
19        WH030     4.204012e+10
20        WH025     4.179291e+10
21        WH033     4.060103e+10
22        WH021     4.031737e+10
23        WH042     4.025606e+10
24        WH008     4.004496e+10
25        WH010     3.968577e+10
26        WH023     3.926176e+10
27        WH038     3.353662e+10
28        WH019     3.319515e+10
29        WH045     3.208173e+10
30        WH004     3.128684e+10
31        WH028     2.985244e+10
32        WH006     2.623093e+10
33        WH011     2.619086e+10
34        WH022     2.579491e+10
35        WH013     2.570682e+10
36        WH014     2.482779e+10
37        WH003     2.464983e+10
38        WH007     2.445538e+10
39        WH005     2.430992e+10
40        WH018     2.389284e+10
41        WH032     2.372648e+10
42        WH044     2.200693e+10
43        WH026     1.759914e+10
44        WH012     1.672627e+10
45        WH001     1.655902e+10
46        WH041     1.568357e+10
47        WH039     1.509201e+10
48        WH002     8.117818e+09
49        WH034     7.781774e+09

In [43]:
query = """
SELECT

Product_ID,

Closing_Stock

FROM Fact_Inventory

WHERE Inventory_Status='Overstock'

ORDER BY Closing_Stock DESC;
"""

pd.read_sql(query, conn)

      Product_ID  Closing_Stock
0       PRD02008           1305
1       PRD00726           1299
2       PRD02030           1291
3       PRD02161           1291
4       PRD02288           1287
...          ...            ...
32187   PRD04840            901
32188   PRD03163            901
32189   PRD03172            901
32190   PRD02601            901
32191   PRD00281            901

[32192 rows x 2 columns]

In [44]:
query = """
SELECT

ROUND(AVG(Stock_Age_Days),2) AS Average_Stock_Age

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Average_Stock_Age
0             183.44

In [45]:
query = """
SELECT

ROUND(SUM(Damage_Quantity),2) AS Damaged_Units

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Damaged_Units
0        14042.0

In [46]:
query = """
SELECT

Warehouse_Transfer,

COUNT(*) AS Total

FROM Fact_Inventory

GROUP BY Warehouse_Transfer;
"""

pd.read_sql(query, conn)

  Warehouse_Transfer   Total
0                 No  189908
1                Yes   10092

In [47]:
query = """
SELECT

ROUND(AVG(Inventory_Turnover),2) AS Average_Inventory_Turnover

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Average_Inventory_Turnover
0                        0.31

In [48]:
query = """
SELECT

ROUND(AVG(Inventory_Turnover),2) AS Average_Inventory_Turnover

FROM Fact_Inventory;
"""

pd.read_sql(query, conn)

   Average_Inventory_Turnover
0                        0.31

In [49]:
query = """
SELECT

ROUND(SUM(Revenue_Generated),2) AS Revenue_Generated

FROM Fact_Marketing;
"""

pd.read_sql(query, conn)

   Revenue_Generated
0       2.413681e+11

In [50]:
query = """
SELECT

ROUND(SUM(Revenue_Generated),2) AS Revenue_Generated

FROM Fact_Marketing;
"""

pd.read_sql(query, conn)

   Revenue_Generated
0       2.413681e+11

In [51]:
query = """
SELECT

Campaign_Type,

ROUND(AVG(ROI),2) AS Average_ROI

FROM Fact_Marketing

GROUP BY Campaign_Type

ORDER BY Average_ROI DESC;
"""

pd.read_sql(query, conn)

  Campaign_Type  Average_ROI
0        Retail      2629.98
1       Digital      2628.77
2      Seasonal      2614.82
3      Festival      2608.24
4   Acquisition      2570.24
5       Loyalty      2564.17
6     Clearance      2554.52

In [52]:
query = """
SELECT

Promotion_Name,

ROUND(SUM(Revenue_Generated),2) AS Revenue

FROM Fact_Marketing

GROUP BY Promotion_Name

ORDER BY Revenue DESC

LIMIT 10;
"""

pd.read_sql(query, conn)

      Promotion_Name       Revenue
0        Summer Sale  2.461202e+10
1      Weekend Offer  2.454027e+10
2    Loyalty Rewards  2.453048e+10
3      App Exclusive  2.431350e+10
4   Diwali Mega Sale  2.417871e+10
5    Monsoon Bonanza  2.405997e+10
6      Year End Sale  2.399149e+10
7       New Customer  2.374879e+10
8  Republic Day Sale  2.373030e+10
9   Independence Day  2.366252e+10

In [53]:
query = """
SELECT

Campaign_Status,

COUNT(*) AS Total_Campaigns,

ROUND(SUM(Revenue_Generated),2) AS Revenue

FROM Fact_Marketing

GROUP BY Campaign_Status;
"""

pd.read_sql(query, conn)

  Campaign_Status  Total_Campaigns       Revenue
0          Active            19933  4.881849e+10
1       Completed            70127  1.688883e+11
2          Paused             9940  2.366122e+10

In [54]:
query = """
SELECT

Marketing_Channel,

ROUND(AVG(CTR)*100,2) AS Average_CTR_Percentage

FROM Fact_Marketing

GROUP BY Marketing_Channel

ORDER BY Average_CTR_Percentage DESC;
"""

pd.read_sql(query, conn)

  Marketing_Channel  Average_CTR_Percentage
0          Meta Ads                    6.50
1             Email                    6.50
2               SMS                    6.49
3        Google Ads                    6.48
4          LinkedIn                    6.47

In [55]:
query = """
SELECT

Marketing_Channel,

ROUND(AVG(Conversion_Rate)*100,2) AS Conversion_Rate_Percentage

FROM Fact_Marketing

GROUP BY Marketing_Channel

ORDER BY Conversion_Rate_Percentage DESC;
"""

pd.read_sql(query, conn)

  Marketing_Channel  Conversion_Rate_Percentage
0          Meta Ads                       37.37
1               SMS                       37.33
2        Google Ads                       37.33
3          LinkedIn                       37.31
4             Email                       37.29

In [56]:
query = """
SELECT

Marketing_Channel,

ROUND(AVG(CPC),2) AS Average_CPC

FROM Fact_Marketing

GROUP BY Marketing_Channel

ORDER BY Average_CPC;
"""

pd.read_sql(query, conn)

  Marketing_Channel  Average_CPC
0               SMS        42.05
1          LinkedIn        42.40
2        Google Ads        42.43
3          Meta Ads        42.48
4             Email        42.60

In [58]:
query = """
SELECT

SUM(Impressions) AS Impressions,

SUM(Clicks) AS Clicks,

SUM(Leads) AS Leads,

SUM(Conversions) AS Conversions

FROM Fact_Marketing;
"""

pd.read_sql(query, conn)

   Impressions     Clicks     Leads  Conversions
0   5043752313  326943824  81423939     30561640

In [59]:
  query = """
SELECT

COUNT(*) AS Total_Tickets

FROM Fact_Support;
"""

pd.read_sql(query, conn)

   Total_Tickets
0         150000

In [62]:
query = """
SELECT

Ticket_Type,

COUNT(*) AS Total_Tickets

FROM Fact_Support

GROUP BY Ticket_Type

ORDER BY Total_Tickets DESC;
"""

pd.read_sql(query, conn)

  Ticket_Type  Total_Tickets
0    Delivery          44801
1     Product          30317
2     Payment          22532
3      Return          22393
4    Warranty          15108
5      Refund          14849

In [63]:
query = """
SELECT

ROUND(AVG(Response_Time_Hours),2) AS Average_Response_Time

FROM Fact_Support;
"""

pd.read_sql(query, conn)

   Average_Response_Time
0                   12.5

In [64]:
query = """
SELECT

ROUND(AVG(Resolution_Time_Hours),2) AS Average_Resolution_Time

FROM Fact_Support;
"""

pd.read_sql(query, conn)

   Average_Resolution_Time
0                    60.53

In [65]:
query = """
SELECT

SLA_Breached,

COUNT(*) AS Total_Tickets

FROM Fact_Support

GROUP BY SLA_Breached;
"""

pd.read_sql(query, conn)

  SLA_Breached  Total_Tickets
0           No          56073
1          Yes          93927

In [66]:
query = """
SELECT

ROUND(AVG(CSAT),2) AS Average_CSAT

FROM Fact_Support;
"""

pd.read_sql(query, conn)

   Average_CSAT
0          3.75

In [67]:
query = """
SELECT

ROUND(AVG(NPS),2) AS Average_NPS

FROM Fact_Support;
"""

pd.read_sql(query, conn)

   Average_NPS
0          5.0

In [68]:
query = """
SELECT

ROUND(SUM(Refund_Amount),2) AS Total_Refund_Amount,

COUNT(*) AS Refund_Requests

FROM Fact_Support

WHERE Refund_Requested='Yes';
"""

pd.read_sql(query, conn)

   Total_Refund_Amount  Refund_Requests
0          229163280.0            22400

In [69]:
query = """
SELECT

Assigned_Agent,

COUNT(*) AS Tickets_Handled,

ROUND(AVG(CSAT),2) AS Average_CSAT,

ROUND(AVG(Resolution_Time_Hours),2) AS Average_Resolution_Time

FROM Fact_Support

GROUP BY Assigned_Agent

ORDER BY Tickets_Handled DESC;
"""

pd.read_sql(query, conn)

  Assigned_Agent  Tickets_Handled  Average_CSAT  Average_Resolution_Time
0        Agent A            18867          3.75                    60.31
1        Agent D            18823          3.75                    60.56
2        Agent B            18814          3.74                    60.52
3        Agent G            18810          3.75                    60.20
4        Agent C            18781          3.74                    60.63
5        Agent F            18767          3.75                    60.79
6        Agent H            18650          3.75                    60.61
7        Agent E            18488          3.75                    60.64

In [70]:
query = """
SELECT

Root_Cause,

COUNT(*) AS Total_Tickets

FROM Fact_Support

GROUP BY Root_Cause

ORDER BY Total_Tickets DESC;
"""

pd.read_sql(query, conn)

         Root_Cause  Total_Tickets
0   Technical Issue          25112
1   Damaged Product          25020
2        Wrong Item          25005
3   Payment Failure          24996
4  Customer Request          24979
5     Late Delivery          24888